# Generated by Django 6.1.1 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilorganizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='horas_estimadas',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
